### ISSUE TITLE
backend: minimize the number of requests if a user is muted then banned

### ISSUE THREAD

**Issue by fyusuf-a** [fyusuf-a/ft_transcendence#20]
If a user is muted with a `POST` to `/memberships`, its role cannot be upgraded to `ban` without a `DELETE` on this route and an additional `POST`. It should be possible to do it with only one HTTP request.

**Comment by tmorris42** [comment]
We should be able to make a `PATCH` request to `/karmas` to change the type from `mute` to `ban`, but it seems like there is a problem with the service on that route. I'm getting a `500` response, so I'll add some tests for this case and put together a fix.
Would a working `PATCH` address this use case?

Another solution is to `POST` a new `karma`, because it _is_ possible to add multiple `karmas`. For example, a user could be muted for 24 hours and then banned for 1 hour. Then once the ban expires, they can come back but still be muted. That allows for a single request to add the ban.

**Comment by tmorris42** [comment]
PR #32 renders this issue obsolete
