### ISSUE TITLE
feat(frontend): fix the error 'member x implicitly has an 'any' type

### ISSUE THREAD

**Issue by fyusuf-a** [fyusuf-a/ft_transcendence#84]
- Make a `npm run lint -- --no-fix --max-warning=0` work as well as mochapack (`npm run test:unit`) by configuring them
- Change a command of the ci in `./.github/workflows/frontend.yml` in step "Test and Lint"

**Comment by tmorris42** [comment]
I've been looking into testing for the `ChatView`. What I've found so far:

- [x]  We have a few lint errors that can be corrected with an explicit type (even if that's `any`)
- [x] I don't have any experience with mochapack, but I think the error from `npm run test:unit` is just because the example test no longer works.
- [ ] `npm run lint` does not lint nested test files, but mochapack will complain about lint errors. I haven't yet found the proper path to add, but it should just be a matter of changing the `.eslintrc` to properly lint **all** test files
- [ ] Update `frontend.yml` to run the tests and proper linting

Even though it is low priority, I would be happy to put out a quick PR for this, unless you'd like to do it yourself
